checkpoints/ACL_cifar100_r18_cifar100
Namespace(batch_size=512, bnNameCnt=1, checkpoint='/home/x/xuxilie/Adversarial-Contrastive-Learning/checkpoints/ACL_DS.pt', cvt_state_dict=False, data='../data', dataset='cifar100', decreasing_lr='10,20', epochs=25, epsilon=0.03137254901960784, eval_only=False, experiment='ACL_cifar100_r18_cifar100', gpu='1', lr=0.01, mode='Ensemble', model='r18', momentum=0.9, num_steps_test=20, num_steps_train=10, pretraining='ACL', resize=32, resume=False, start_epoch=0, step_size=0.00784313725490196, test_batch_size=512, test_frequency=0, weight_decay=0.0002)
Finetuning mode: SLF
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Traceback (most recent call last):
  File "finetuning_eval.py", line 128, in <module>
    model, optimizer, scheduler = get_model(args, num_classes, mode, log, device=device)
  File "/home/x/xuxilie/RobSSL_Benchmark/utils.py", line 547, in get_model
    model = resnet18(num_classes=num_classes).to(device)
  File "/home/x/xuxilie/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 989, in to
    return self._apply(convert)
  File "/home/x/xuxilie/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/x/xuxilie/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 688, in _apply
    self._buffers[key] = fn(buf)
  File "/home/x/xuxilie/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
